ssh and webserver

diff --git a/0x0B-ssh/1-create_ssh_key_pair b/0x0B-ssh/1-create_ssh_key_pair
--- a/0x0B-ssh/1-create_ssh_key_pair
+++ b/0x0B-ssh/1-create_ssh_key_pair
@@ -1,4 +1,10 @@
 #!/usr/bin/env bash
-# Bash script that creates an RSA key pair
-#ssh-keygen -b 4096 -P betty -f school
-ssh-keygen -t rsa -b 4096 -P betty -f school
+# This script creates an RSA key pair with a passphrase.
+
+ssh-keygen -t rsa -b 4096 -f school -N "betty"
+
+if [ $? -eq 0 ]; then
+    echo "RSA key pair 'school' with passphrase 'betty' created successfully."
+else
+    echo "Failed to create RSA key pair."
+fi
